/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testing;

/**
 *
 * @author amritpal
 */
public class Tictactoe extends javax.swing.JFrame {

    /**
     * Creates new form calculator
     *
    */
    
    int currentChance = 1;
    
    public Tictactoe() {
	setTitle("Tic Tac Toe Game");
	initComponents();
	
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        box1 = new javax.swing.JButton();
        box2 = new javax.swing.JButton();
        box3 = new javax.swing.JButton();
        box6 = new javax.swing.JButton();
        box4 = new javax.swing.JButton();
        box5 = new javax.swing.JButton();
        box8 = new javax.swing.JButton();
        box7 = new javax.swing.JButton();
        box9 = new javax.swing.JButton();
        infoLabel = new javax.swing.JLabel();
        resetGameBtn = new javax.swing.JButton();
        resetMatchBtn = new javax.swing.JButton();
        staticCountLabel = new javax.swing.JLabel();
        oWins = new javax.swing.JLabel();
        xWins = new javax.swing.JLabel();
        staticTitle = new javax.swing.JLabel();
        xLabel = new javax.swing.JLabel();
        oLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tic Tac Toe Game");
        setResizable(false);

        box1.setFont(new java.awt.Font("Ubuntu", 1, 72)); // NOI18N
        box1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box1ActionPerformed(evt);
            }
        });

        box2.setFont(new java.awt.Font("Ubuntu", 1, 72)); // NOI18N
        box2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box2ActionPerformed(evt);
            }
        });

        box3.setFont(new java.awt.Font("Ubuntu", 1, 72)); // NOI18N
        box3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box3ActionPerformed(evt);
            }
        });

        box6.setFont(new java.awt.Font("Ubuntu", 1, 72)); // NOI18N
        box6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box6ActionPerformed(evt);
            }
        });

        box4.setFont(new java.awt.Font("Ubuntu", 1, 72)); // NOI18N
        box4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box4ActionPerformed(evt);
            }
        });

        box5.setFont(new java.awt.Font("Ubuntu", 1, 72)); // NOI18N
        box5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box5ActionPerformed(evt);
            }
        });

        box8.setFont(new java.awt.Font("Ubuntu", 1, 72)); // NOI18N
        box8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box8ActionPerformed(evt);
            }
        });

        box7.setFont(new java.awt.Font("Ubuntu", 1, 72)); // NOI18N
        box7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box7ActionPerformed(evt);
            }
        });

        box9.setFont(new java.awt.Font("Ubuntu", 1, 72)); // NOI18N
        box9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                box9ActionPerformed(evt);
            }
        });

        infoLabel.setFont(new java.awt.Font("Ubuntu", 2, 36)); // NOI18N
        infoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infoLabel.setText("X Player's Turn");
        infoLabel.setBorder(new javax.swing.border.MatteBorder(null));

        resetGameBtn.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        resetGameBtn.setText("Reset Game");
        resetGameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetGameBtnActionPerformed(evt);
            }
        });

        resetMatchBtn.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        resetMatchBtn.setText("Reset Match");
        resetMatchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetMatchBtnActionPerformed(evt);
            }
        });

        staticCountLabel.setFont(new java.awt.Font("Ubuntu", 3, 24)); // NOI18N
        staticCountLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        staticCountLabel.setText("Win Count");
        staticCountLabel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        oWins.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        oWins.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        oWins.setText("0");
        oWins.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        xWins.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        xWins.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        xWins.setText("0");
        xWins.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        staticTitle.setFont(new java.awt.Font("Gayathri Thin", 3, 36)); // NOI18N
        staticTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        staticTitle.setText("Tic Tac Toe Game");
        staticTitle.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        xLabel.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        xLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        xLabel.setText("X :");

        oLabel.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N
        oLabel.setText("O :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(box1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(box2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(box3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(infoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(xLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(xWins, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(staticCountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(oLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(oWins, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(staticTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(box4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(box5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(box6, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(box7, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(box8, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(box9, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(resetGameBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(resetMatchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(staticTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(oLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(xLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(oWins, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(xWins, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(staticCountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(infoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(box1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(box2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(box3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(box4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(box5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(box6, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(box7, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(box8, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(box9, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resetMatchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resetGameBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        box1.getAccessibleContext().setAccessibleName("box1");
        box2.getAccessibleContext().setAccessibleName("box2");
        box3.getAccessibleContext().setAccessibleName("box3");
        box6.getAccessibleContext().setAccessibleName("box6");
        box6.getAccessibleContext().setAccessibleDescription("");
        box4.getAccessibleContext().setAccessibleName("box4");
        box5.getAccessibleContext().setAccessibleName("box5");
        box8.getAccessibleContext().setAccessibleName("box8");
        box7.getAccessibleContext().setAccessibleName("box7");
        box9.getAccessibleContext().setAccessibleName("box9");
        infoLabel.getAccessibleContext().setAccessibleName("infoLabel");
        resetGameBtn.getAccessibleContext().setAccessibleName("resetGameBtn");
        resetMatchBtn.getAccessibleContext().setAccessibleName("resetMatchBtn");
        staticCountLabel.getAccessibleContext().setAccessibleName("staticCountLabel");
        oWins.getAccessibleContext().setAccessibleName("oWins");
        xWins.getAccessibleContext().setAccessibleName("xWins");
        staticTitle.getAccessibleContext().setAccessibleName("staticTitle");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void checkWin(){
	char winner = ' ';
	String box[] = {box1.getText(),box2.getText(),box3.getText(),box4.getText(),box5.getText(),
	    box6.getText(),box7.getText(),box8.getText(),box9.getText()};
	if((box[0]==box[4] && box[4]==box[8] || box[1]==box[4] && box[4]==box[7]
		|| box[2]==box[4] && box[4]==box[6] || box[5]==box[4] && box[4]==box[3]) && box[4] != ""){
	    winner = box[4].charAt(0);
	} else if((box[0]==box[1] && box[1]==box[2] || box[0]==box[3] && box[3]==box[6]) && box[0] != ""){
	    winner = box[0].charAt(0);
	} else if((box[8]==box[5] && box[5]==box[2] || box[8]==box[7] && box[7]==box[6]) && box[8] != ""){
	    winner = box[8].charAt(0);
	} else{
	    int rowsCheck[] = {0,0,0}; // to check if all box are filled
	    for(int i = 0;i<=6; i+=3){
		if(box[i] != "" && box[i+1] != "" && box[i+2] != ""){
		    if(i==0){
			rowsCheck[0] = 1;
		    } else if(i==3){
			rowsCheck[1] = 1;
		    } else{
			rowsCheck[2] = 1;
		    }    
		}
	    }
	    
	    if(rowsCheck[0]==rowsCheck[1] && rowsCheck[1]==rowsCheck[2] && rowsCheck[2]==1){
		winner = 'd';
	    }
	}
	
	if(winner != ' '){
	    box1.setEnabled(false);
	    box2.setEnabled(false);
	    box3.setEnabled(false);
	    box4.setEnabled(false);
	    box5.setEnabled(false);
	    box6.setEnabled(false);
	    box7.setEnabled(false);
	    box8.setEnabled(false);
	    box9.setEnabled(false);
	    
	    if(winner == 'd'){
		infoLabel.setText("Game is Draw!");
	    } else if(winner == 'X'){
		String xWinCount =Integer.toString(Integer.parseInt(xWins.getText())+1);
		xWins.setText(xWinCount);
		infoLabel.setText("X Player wins!");
	    } else{
		String oWinCount =Integer.toString(Integer.parseInt(oWins.getText())+1);
		oWins.setText(oWinCount);
		infoLabel.setText("O Player wins!");
	    }
	}
	
    }
    
    private void box3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box3ActionPerformed
        // TODO add your handling code here:
	if(box3.getText() == ""){
	    if(currentChance == 1){
		box3.setText("X");
		currentChance = 0;
		infoLabel.setText("O Player's Turn");
		
	    } else{
		box3.setText("O");
		currentChance = 1;
		infoLabel.setText("X Player's Turn");
	    }
	}
	checkWin();
    }//GEN-LAST:event_box3ActionPerformed

    private void box6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box6ActionPerformed
        // TODO add your handling code here:
	if(box6.getText() == ""){
	    if(currentChance == 1){
		box6.setText("X");
		currentChance = 0;
		infoLabel.setText("O Player's Turn");
	    } else{
		box6.setText("O");
		currentChance = 1;
		infoLabel.setText("X Player's Turn");
	    }
	}
	checkWin();
    }//GEN-LAST:event_box6ActionPerformed

    private void box9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box9ActionPerformed
        // TODO add your handling code here:
	if(box9.getText() == ""){
	    if(currentChance == 1){
		box9.setText("X");
		currentChance = 0;
		infoLabel.setText("O Player's Turn");
	    } else{
		box9.setText("O");
		currentChance = 1;
		infoLabel.setText("X Player's Turn");
	    }
	}
	checkWin();
	
    }//GEN-LAST:event_box9ActionPerformed

    private void box1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box1ActionPerformed
        // TODO add your handling code here:
	if(box1.getText() == ""){
	    if(currentChance == 1){
		box1.setText("X");
		currentChance = 0;
		infoLabel.setText("O Player's Turn");
	    } else{
		box1.setText("O");
		currentChance = 1;
		infoLabel.setText("X Player's Turn");
	    }
	}
	checkWin();
    }//GEN-LAST:event_box1ActionPerformed

    private void resetGameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetGameBtnActionPerformed
        // TODO add your handling code here:
	infoLabel.setText("X Player's Turn");
	currentChance = 1;
	
	box1.setText("");
	box2.setText("");
	box3.setText("");
	box4.setText("");
	box5.setText("");
	box6.setText("");
	box7.setText("");
	box8.setText("");
	box9.setText("");
	xWins.setText("0");
	oWins.setText("0");
	
	box1.setEnabled(true);
	box2.setEnabled(true);
	box3.setEnabled(true);
	box4.setEnabled(true);
	box5.setEnabled(true);
	box6.setEnabled(true);
	box7.setEnabled(true);
	box8.setEnabled(true);
	box9.setEnabled(true);
    }//GEN-LAST:event_resetGameBtnActionPerformed

    private void resetMatchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetMatchBtnActionPerformed
        // TODO add your handling code here:
	infoLabel.setText("X Player's Turn");
	currentChance = 1;
	
	box1.setText("");
	box2.setText("");
	box3.setText("");
	box4.setText("");
	box5.setText("");
	box6.setText("");
	box7.setText("");
	box8.setText("");
	box9.setText("");
	
	box1.setEnabled(true);
	box2.setEnabled(true);
	box3.setEnabled(true);
	box4.setEnabled(true);
	box5.setEnabled(true);
	box6.setEnabled(true);
	box7.setEnabled(true);
	box8.setEnabled(true);
	box9.setEnabled(true);
    }//GEN-LAST:event_resetMatchBtnActionPerformed

    private void box2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box2ActionPerformed
        // TODO add your handling code here:
	if(box2.getText() == ""){
	    if(currentChance == 1){
		box2.setText("X");
		currentChance = 0;
		infoLabel.setText("O Player's Turn");
	    } else{
		box2.setText("O");
		currentChance = 1;
		infoLabel.setText("X Player's Turn");
	    }
	}
	checkWin();
    }//GEN-LAST:event_box2ActionPerformed

    private void box4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box4ActionPerformed
        // TODO add your handling code here:
	if(box4.getText() == ""){
	    if(currentChance == 1){
		box4.setText("X");
		currentChance = 0;
		infoLabel.setText("O Player's Turn");
	    } else{
		box4.setText("O");
		currentChance = 1;
		infoLabel.setText("X Player's Turn");
	    }
	}
	checkWin();
    }//GEN-LAST:event_box4ActionPerformed

    private void box5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box5ActionPerformed
        // TODO add your handling code here:
	if(box5.getText() == ""){
	    if(currentChance == 1){
		box5.setText("X");
		currentChance = 0;
		infoLabel.setText("O Player's Turn");
	    } else{
		box5.setText("O");
		currentChance = 1;
		infoLabel.setText("X Player's Turn");
	    }
	}
	checkWin();
    }//GEN-LAST:event_box5ActionPerformed

    private void box7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box7ActionPerformed
        // TODO add your handling code here:
	if(box7.getText() == ""){
	    if(currentChance == 1){
		box7.setText("X");
		currentChance = 0;
		infoLabel.setText("O Player's Turn");
	    } else{
		box7.setText("O");
		currentChance = 1;
		infoLabel.setText("X Player's Turn");
	    }
	}
	checkWin();
    }//GEN-LAST:event_box7ActionPerformed

    private void box8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_box8ActionPerformed
        // TODO add your handling code here:
	if(box8.getText() == ""){
	    if(currentChance == 1){
		box8.setText("X");
		currentChance = 0;
		infoLabel.setText("O Player's Turn");
	    } else{
		box8.setText("O");
		currentChance = 1;
		infoLabel.setText("X Player's Turn");
	    }
	}
	checkWin();
    }//GEN-LAST:event_box8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/* Set the Nimbus look and feel */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Metal".equals(info.getName())) {
//		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.gtk.GTKLookAndFeel");
		    break;
		}
	    }
	} catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(Tictactoe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(Tictactoe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(Tictactoe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(Tictactoe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>
	//</editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable() {
	    public void run() {
		new Tictactoe().setVisible(true);
	    }
	});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton box1;
    private javax.swing.JButton box2;
    private javax.swing.JButton box3;
    private javax.swing.JButton box4;
    private javax.swing.JButton box5;
    private javax.swing.JButton box6;
    private javax.swing.JButton box7;
    private javax.swing.JButton box8;
    private javax.swing.JButton box9;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JLabel oLabel;
    private javax.swing.JLabel oWins;
    private javax.swing.JButton resetGameBtn;
    private javax.swing.JButton resetMatchBtn;
    private javax.swing.JLabel staticCountLabel;
    private javax.swing.JLabel staticTitle;
    private javax.swing.JLabel xLabel;
    private javax.swing.JLabel xWins;
    // End of variables declaration//GEN-END:variables
}
